spring:
  redis:
    password: zhaobaolong1
    host: baiduyun
    port: 6379
    timeout: 1000
    pool:
      max-active: 10
      max-idle: 8
      min-idle: 2
      max-wait: 100
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200
    url: jdbc:mysql://106.13.10.6:3306/springboot-project?useSSL=false&serverTimezone=UTC&characterEncoding=utf8
  activiti:
    database-schema-update: true
